DROP PROCEDURE IF EXISTS sp_TRUNCATE_POINTS;

CREATE OR REPLACE PROCEDURE sp_TRUNCATE_POINTS()
LANGUAGE plpgsql
AS $$
BEGIN
    TRUNCATE TABLE "Points";
    TRUNCATE TABLE "WorldPoints";
END;
$$;

DROP PROCEDURE IF EXISTS sp_RESET_DATABASE;

CREATE OR REPLACE PROCEDURE sp_RESET_DATABASE()
    LANGUAGE plpgsql
AS $$
BEGIN
    TRUNCATE TABLE "Points" RESTART IDENTITY;
    TRUNCATE TABLE "WorldPoints" RESTART IDENTITY;
    TRUNCATE TABLE "Provinces" RESTART IDENTITY;
    TRUNCATE TABLE "LakePoints" RESTART IDENTITY;
    TRUNCATE TABLE "RiverPoints" RESTART IDENTITY;
    TRUNCATE TABLE "Lakes" RESTART IDENTITY;
    TRUNCATE TABLE "Rivers" RESTART IDENTITY;
    TRUNCATE TABLE "RenderEdges" RESTART IDENTITY;
    TRUNCATE TABLE "Waterfalls" RESTART IDENTITY;
END;
$$;

